"""environment.py — Phase 5 (secure environment) deterministic service layer.

The three-layer model (kept strictly separate per the Phase 5 brief):

    Layer 1  METADATA    what variables exist          environment_variables
    Layer 2  PERMISSIONS who may retrieve what         environment_access
    Layer 3  VALUES      the actual secret bytes       scaffold_secrets (secret_store.py)

Everything in THIS module is deterministic plain SQL/Python (repo rule #3) over
layers 1-2; layer 3 is delegated entirely to services/secret_store.py, which is
the only module allowed to touch ciphertext.

Audit trail (Feature 8): access decisions are written to the existing `events`
table as new additive event types — `env_variable_defined`, `env_value_set`,
`env_access_granted`, `env_access_revoked`, `env_secret_requested`,
`env_secret_access_denied`, `env_secret_retrieved`, `env_secret_rotated`,
`env_variable_removed`. Payloads carry ids, names, and outcomes ONLY — the
Phase 5 hard rule "log that access happened, never the secret itself" is
enforced here: no code path can put a value into a payload because values
never pass through this module at all.
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import EnvironmentAccess, EnvironmentVariable, Event, Project, User
from app.services import secret_store

ENV_KEY_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
MAX_ENV_KEY_LEN = 120
MAX_ENV_DESCRIPTION_LEN = 500

EVENT_VARIABLE_DEFINED = "env_variable_defined"
EVENT_VALUE_SET = "env_value_set"
EVENT_ACCESS_GRANTED = "env_access_granted"
EVENT_ACCESS_REVOKED = "env_access_revoked"
EVENT_SECRET_REQUESTED = "env_secret_requested"
EVENT_SECRET_DENIED = "env_secret_access_denied"
EVENT_SECRET_RETRIEVED = "env_secret_retrieved"
EVENT_SECRET_ROTATED = "env_secret_rotated"
EVENT_VARIABLE_REMOVED = "env_variable_removed"


class EnvKeyInvalid(ValueError):
    """The variable name fails the shape rule (SCREAMING_SNAKE_CASE)."""


# ---------------------------------------------------------------------------
# Pure helpers (no DB, no clock reads — unit-testable without Postgres)
# ---------------------------------------------------------------------------

def validate_key(key: str) -> str:
    """SCREAMING_SNAKE_CASE only — an env var key is not free text (it lands in
    generated .env.example files and audit events)."""
    k = (key or "").strip()
    if not k or len(k) > MAX_ENV_KEY_LEN or not ENV_KEY_RE.fullmatch(k):
        raise EnvKeyInvalid(
            "key must be SCREAMING_SNAKE_CASE (letters, digits, underscores, "
            "starting with a letter)"
        )
    return k


def status_of(variable: dict, configured: bool) -> str:
    """Dashboard status word — exactly the four the Phase 5 brief lists.
    Pure function so the UI wording can never drift from the API."""
    if configured:
        return "configured"
    return "required_missing" if variable.get("required") else "optional_missing"


def display_status(status: str) -> str:
    """Human label for the status word (UI copy lives next to the logic)."""
    return {
        "configured": "Configured",
        "required_missing": "Required · Missing",
        "optional_missing": "Optional · Not configured",
    }[status]


def template_lines(rows: list[dict]) -> str:
    """`.env.example` body: names with EMPTY values, never a value, ever.
    The description is available separately (the `description` metadata field
    is served by GET /environment and the template endpoint's header)."""
    return "\n".join(f"{r['key']}=" for r in rows)


def pull_file_body(project_name: str, rows: list[dict]) -> str:
    """Body of the generated `.env.scaffold` file for `scaffold env pull`.
    Values come from the AUTHORIZED retrieval — the file is written by the
    developer's local command, never rendered in any UI. Non-secret values and
    secrets live here side by side: the file itself is the controlled artifact
    (gitignored pattern, review-before-use workflow)."""
    lines = [
        f"# .env.scaffold — generated by Scaffold env pull for project '{project_name}'.",
        "# Review before use. NEVER commit this file (.env* is gitignored; verify your",
        "# repo's .gitignore covers it). Scaffold's canonical template lives in .env.example.",
        "",
    ]
    for r in rows:
        desc = (r.get("description") or "").strip()
        if desc:
            lines.append(f"# {desc}")
        lines.append(f"{r['key']}={r.get('value') or ''}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# DB-backed deterministic operations
# ---------------------------------------------------------------------------

def _event(db: Session, project_id: uuid.UUID, type_: str, payload: dict) -> None:
    db.add(Event(project_id=project_id, type=type_, payload=payload))


def get_project(db: Session, project_id: uuid.UUID) -> Project:
    project = db.get(Project, project_id)
    if not project:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="project not found")
    return project


def require_member(db: Session, project_id: uuid.UUID, user_id: uuid.UUID | None) -> User:
    """The requester must be an ACTIVE member of THIS project — the Phase 5
    membership check. Project isolation: a user id from another project (or a
    removed member) can never see this project's environment."""
    if user_id is None:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail="user_id is required")
    user = db.get(User, user_id)
    if not user or user.project_id != project_id or user.membership_status == "removed":
        from fastapi import HTTPException

        raise HTTPException(
            status_code=403,
            detail="requester is not an active member of this project",
        )
    return user


def require_owner_if_set(project: Project, requesting_user_id: uuid.UUID | None) -> None:
    """Owner-gate for metadata/grant mutations — the exact placeholder trust
    model every other owner-gated route uses (see routes/team.py): compared
    server-side to projects.owner_user_id; open until an owner is claimed."""
    if project.owner_user_id is None:
        return
    if requesting_user_id is None or requesting_user_id != project.owner_user_id:
        from fastapi import HTTPException

        raise HTTPException(status_code=403, detail="only the project owner can perform this action")


def list_variables(db: Session, project_id: uuid.UUID) -> list[dict]:
    """Layer 1 + a computed configured flag (layer 3 touched ONLY as a boolean —
    never a value). Bounded output; safe for the dashboard."""
    rows = db.scalars(
        select(EnvironmentVariable)
        .where(EnvironmentVariable.project_id == project_id)
        .order_by(EnvironmentVariable.key.asc())
    ).all()
    return [
        {
            "id": str(v.id),
            "project_id": str(v.project_id),
            "key": v.key,
            "description": v.description,
            "required": v.required,
            "is_secret": v.is_secret,
            "created_by": str(v.created_by) if v.created_by else None,
            "created_at": v.created_at.isoformat(),
            "updated_at": v.updated_at.isoformat(),
            "configured": has_value(db, v.id),
        }
        for v in rows
    ]


def has_value(db: Session, environment_variable_id: uuid.UUID) -> bool:
    """Configured = a ciphertext row exists. This is the ONLY bit of layer 3
    that metadata consumers ever learn (a boolean, never bytes)."""
    from sqlalchemy import text

    row = db.execute(
        text(
            "SELECT 1 FROM scaffold_secrets.environment_secrets "
            "WHERE environment_variable_id = :id LIMIT 1"
        ),
        {"id": environment_variable_id},
    ).first()
    return row is not None


def define_variable(
    db: Session,
    project_id: uuid.UUID,
    key: str,
    description: str | None,
    required: bool,
    is_secret: bool,
    created_by: uuid.UUID | None,
    value: str | None = None,
) -> dict:
    """Create (or re-describe) a variable. With `value`, the initial value is
    stored through the secret store in the same transaction."""
    try:
        clean_key = validate_key(key)
    except EnvKeyInvalid as exc:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail=str(exc)) from exc

    existing = db.scalar(
        select(EnvironmentVariable).where(
            EnvironmentVariable.project_id == project_id, EnvironmentVariable.key == clean_key
        )
    )
    if existing:
        from fastapi import HTTPException

        raise HTTPException(status_code=409, detail=f"{clean_key} is already defined for this project")

    var = EnvironmentVariable(
        project_id=project_id,
        key=clean_key,
        description=(description or "").strip() or None,
        required=required,
        is_secret=is_secret,
        created_by=created_by,
    )
    db.add(var)
    db.flush()

    if value is not None:
        try:
            secret_store.set_value(db, var.id, value)
        except secret_store.SecretStoreUnavailable:
            db.rollback()
            from fastapi import HTTPException

            raise HTTPException(
                status_code=503,
                detail="secret store unavailable: pgcrypto keyring missing — secret values cannot be stored",
            ) from None

    _event(
        db,
        project_id,
        EVENT_VARIABLE_DEFINED,
        {"key": clean_key, "required": required, "is_secret": is_secret,
         "created_by": str(created_by) if created_by else None},
    )
    db.commit()
    return variable_out(db, var)


def variable_out(db: Session, var: EnvironmentVariable) -> dict:
    return {
        "id": str(var.id),
        "project_id": str(var.project_id),
        "key": var.key,
        "description": var.description,
        "required": var.required,
        "is_secret": var.is_secret,
        "created_by": str(var.created_by) if var.created_by else None,
        "created_at": var.created_at.isoformat(),
        "updated_at": var.updated_at.isoformat(),
        "configured": has_value(db, var.id),
    }


def get_variable(db: Session, project_id: uuid.UUID, variable_id: uuid.UUID) -> EnvironmentVariable:
    var = db.scalar(
        select(EnvironmentVariable).where(
            EnvironmentVariable.id == variable_id, EnvironmentVariable.project_id == project_id
        )
    )
    if not var:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="environment variable not found")
    return var


def update_variable(
    db: Session,
    project: Project,
    var: EnvironmentVariable,
    requesting_user_id: uuid.UUID | None,
    description: str | None = None,
    required: bool | None = None,
    is_secret: bool | None = None,
    value: str | None = None,
    value_changed: bool = False,
) -> dict:
    """PATCH metadata and/or the value (value-only PATCH == rotation). Owner-gated
    once an owner exists. Value changes flow through secret_store only; the
    audit event records that it happened, never the value."""
    require_owner_if_set(project, requesting_user_id)

    changed: dict = {}
    if description is not None:
        var.description = description.strip() or None
        changed["description"] = True
    if required is not None:
        var.required = required
        changed["required"] = required
    if is_secret is not None:
        var.is_secret = is_secret
        changed["is_secret"] = is_secret

    had_value = has_value(db, var.id)
    if value_changed:
        try:
            secret_store.set_value(db, var.id, value or "")
        except secret_store.SecretStoreUnavailable:
            db.rollback()
            from fastapi import HTTPException

            raise HTTPException(
                status_code=503,
                detail="secret store unavailable: pgcrypto keyring missing — secret values cannot be stored",
            ) from None
        var.updated_at = datetime.now()
        _event(
            db,
            project.id,
            EVENT_SECRET_ROTATED if had_value else EVENT_VALUE_SET,
            {"key": var.key, "via": "patch"},
        )
    elif changed:
        var.updated_at = datetime.now()
        _event(db, project.id, "env_variable_updated", {"key": var.key, **changed})
    db.commit()
    return variable_out(db, var)


def remove_variable(
    db: Session,
    project: Project,
    var: EnvironmentVariable,
    requesting_user_id: uuid.UUID | None,
) -> dict:
    """DELETE metadata + ciphertext (CASCADE handles the grant rows; the
    ciphertext row is removed through the secret store before the ORM delete)."""
    require_owner_if_set(project, requesting_user_id)
    secret_store.clear_value(db, var.id)
    db.delete(var)
    _event(db, project.id, EVENT_VARIABLE_REMOVED, {"key": var.key})
    db.commit()
    return {"removed": True, "id": str(var.id), "key": var.key}


# ---------------------------------------------------------------------------
# Layer 2 — grants (access control)
# ---------------------------------------------------------------------------

def grant_access(
    db: Session,
    project: Project,
    var: EnvironmentVariable,
    user_id: uuid.UUID,
    granted_by: uuid.UUID | None,
) -> dict:
    """Allow ONE member/agent of THIS project to retrieve ONE variable. No
    blanket project-member access is ever implied (Phase 5 Feature 3)."""
    target = db.get(User, user_id)
    if not target or target.project_id != project.id:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail="user_id is not a member of this project")

    existing = db.scalar(
        select(EnvironmentAccess).where(
            EnvironmentAccess.environment_variable_id == var.id,
            EnvironmentAccess.user_id == user_id,
        )
    )
    if existing:
        return grant_out(existing, var, target)

    row = EnvironmentAccess(
        environment_variable_id=var.id, user_id=user_id, granted_by=granted_by
    )
    db.add(row)
    db.flush()
    _event(
        db,
        project.id,
        EVENT_ACCESS_GRANTED,
        {"key": var.key, "user_id": str(user_id), "granted_by": str(granted_by) if granted_by else None},
    )
    db.commit()
    return grant_out(row, var, target)


def revoke_access(
    db: Session,
    project: Project,
    grant: EnvironmentAccess,
    var: EnvironmentVariable,
    requesting_user_id: uuid.UUID | None,
) -> dict:
    require_owner_if_set(project, requesting_user_id)
    db.delete(grant)
    _event(
        db,
        project.id,
        EVENT_ACCESS_REVOKED,
        {"key": var.key, "user_id": str(grant.user_id)},
    )
    db.commit()
    return {"revoked": True, "id": str(grant.id)}


def get_grant(db: Session, project_id: uuid.UUID, grant_id: uuid.UUID) -> tuple[EnvironmentAccess, EnvironmentVariable] | None:
    row = db.get(EnvironmentAccess, grant_id)
    if not row:
        return None
    var = db.get(EnvironmentVariable, row.environment_variable_id)
    if not var or var.project_id != project_id:
        return None
    return row, var


def grants_for_variable(db: Session, var: EnvironmentVariable) -> list[dict]:
    rows = db.scalars(
        select(EnvironmentAccess).where(EnvironmentAccess.environment_variable_id == var.id)
    ).all()
    users = {
        u.id: u
        for u in db.scalars(
            select(User).where(User.id.in_([r.user_id for r in rows] or [uuid.uuid4()]))
        ).all()
    }
    return [
        {
            "id": str(r.id),
            "environment_variable_id": str(r.environment_variable_id),
            "key": var.key,
            "user_id": str(r.user_id),
            "user_name": users.get(r.user_id).name if users.get(r.user_id) else None,
            "granted_by": str(r.granted_by) if r.granted_by else None,
            "created_at": r.created_at.isoformat(),
        }
        for r in rows
    ]


def grant_out(row: EnvironmentAccess, var: EnvironmentVariable, user: User) -> dict:
    return {
        "id": str(row.id),
        "environment_variable_id": str(row.environment_variable_id),
        "key": var.key,
        "user_id": str(row.user_id),
        "user_name": user.name,
        "granted_by": str(row.granted_by) if row.granted_by else None,
        "created_at": row.created_at.isoformat(),
    }


# ---------------------------------------------------------------------------
# Layer 3 — the request flow (Feature 4) and authorized retrieval (Feature 5/10)
# ---------------------------------------------------------------------------

def request_secret(
    db: Session,
    project: Project,
    var: EnvironmentVariable,
    user: User,
) -> dict:
    """Agent/developer request flow: membership is already checked by the
    caller (require_member); this checks the GRANT, audits the outcome, and —
    only when authorized — returns the decrypted value.

    The value NEVER lands in an event payload, a log line, or any list
    endpoint: the retrieval response is the one and only carrier.
    """
    has_grant = db.scalar(
        select(EnvironmentAccess.id).where(
            EnvironmentAccess.environment_variable_id == var.id,
            EnvironmentAccess.user_id == user.id,
        )
    ) is not None

    _event(
        db,
        project.id,
        EVENT_SECRET_REQUESTED,
        {"key": var.key, "user_id": str(user.id), "user_name": user.name, "kind": user.kind},
    )
    if not has_grant:
        _event(
            db,
            project.id,
            EVENT_SECRET_DENIED,
            {"key": var.key, "user_id": str(user.id), "reason": "no access grant"},
        )
        db.commit()
        from fastapi import HTTPException

        raise HTTPException(
            status_code=403,
            detail="no access grant for this variable — ask the project owner to grant access",
        )

    try:
        value = secret_store.get_value(db, var.id)
    except Exception as exc:  # broken keyring/extension must fail closed, loudly
        db.rollback()
        from fastapi import HTTPException

        raise HTTPException(
            status_code=503,
            detail="secret store unavailable: value could not be decrypted",
        ) from exc

    if value is None:
        db.commit()
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="variable is defined but not configured")

    _event(
        db,
        project.id,
        EVENT_SECRET_RETRIEVED,
        {"key": var.key, "user_id": str(user.id)},
    )
    db.commit()
    return {"key": var.key, "value": value}


def pull_environment(db: Session, project: Project, user: User) -> dict:
    """`scaffold env pull` core: every variable this member is AUTHORIZED for.
    No grant -> the variable is omitted entirely (never an error, never a
    value) so the command's output is exactly the safe superset of the
    caller's entitlement."""
    rows = db.execute(
        select(EnvironmentVariable, EnvironmentAccess.id)
        .join(EnvironmentAccess, EnvironmentAccess.environment_variable_id == EnvironmentVariable.id)
        .where(
            EnvironmentVariable.project_id == project.id,
            EnvironmentAccess.user_id == user.id,
        )
        .order_by(EnvironmentVariable.key.asc())
    ).all()
    out = []
    for var, _grant_id in rows:
        try:
            value = secret_store.get_value(db, var.id)
        except Exception:
            db.rollback()
            value = None
        out.append(
            {
                "key": var.key,
                "value": value,
                "description": var.description,
                "is_secret": var.is_secret,
            }
        )
    granted = len(out)
    _event(
        db,
        project.id,
        EVENT_SECRET_RETRIEVED,
        {"key": "*", "user_id": str(user.id), "count": granted, "via": "env_pull"},
    )
    db.commit()
    from sqlalchemy import func

    total_count = db.scalar(
        select(func.count()).where(EnvironmentVariable.project_id == project.id)
    ) or 0
    return {
        "project_id": str(project.id),
        "project_name": project.name,
        "values": out,
        "granted_count": granted,
        "total_count": total_count,
    }


# ---------------------------------------------------------------------------
# Template generation (Feature 6) — deterministic, value-free
# ---------------------------------------------------------------------------

def build_template(db: Session, project_id: uuid.UUID) -> dict:
    """`.env.example` contents: names + EMPTY values + a comment header from
    the metadata descriptions. Secrets and non-secrets look identical here —
    by design; a template carries no information about secretness."""
    rows = db.scalars(
        select(EnvironmentVariable)
        .where(EnvironmentVariable.project_id == project_id)
        .order_by(EnvironmentVariable.key.asc())
    ).all()
    return {
        "project_id": str(project_id),
        "project_name": None,  # filled by the route (needs the project row)
        "filename": ".env.example",
        "variables": [{"key": r.key, "description": r.description} for r in rows],
        "content": template_lines(
            [{"key": r.key} for r in rows]
        ),
        "count": len(rows),
    }


# ---------------------------------------------------------------------------
# Audit readers (Feature 8) — bounded, value-free by construction
# ---------------------------------------------------------------------------

AUDIT_EVENT_TYPES = (
    EVENT_VARIABLE_DEFINED,
    EVENT_VALUE_SET,
    EVENT_ACCESS_GRANTED,
    EVENT_ACCESS_REVOKED,
    EVENT_SECRET_REQUESTED,
    EVENT_SECRET_DENIED,
    EVENT_SECRET_RETRIEVED,
    EVENT_SECRET_ROTATED,
    EVENT_VARIABLE_REMOVED,
    "env_variable_updated",
)


def audit_log(db: Session, project_id: uuid.UUID, limit: int = 50) -> list[dict]:
    """Newest audit events first. Payloads are stored value-free (see the event
    writers above) — this is a plain read, nothing to scrub."""
    rows = db.scalars(
        select(Event)
        .where(
            Event.project_id == project_id,
            Event.type.in_(AUDIT_EVENT_TYPES),
        )
        .order_by(Event.created_at.desc())
        .limit(min(max(limit, 1), 200))
    ).all()
    return [
        {
            "id": str(e.id),
            "type": e.type,
            "payload": e.payload,
            "created_at": e.created_at.isoformat(),
        }
        for e in rows
    ]
